version: '3.9'

services:
  db:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "phonebook"
      MYSQL_USER: "rise"
      MYSQL_PASSWORD: "shine"

  server:
    image: server
    build: 
      context: .
      dockerfile: ./Dockerfile_server
    depends_on:
      - db
    ports:
      - 9000:9000
    command: sh -c "dockerize -wait tcp://db:3306 -timeout 300s -wait-retry-interval 30s /app/main/main"