version: '3.9'

services:
  db:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ./data:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "phonebook"
      MYSQL_USER: "rise"
      MYSQL_PASSWORD: "shine"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD

  server:
    image: server
    volumes:
      - ./logs:/app/main/logs/ 
    build: 
      context: .
      dockerfile: ./Dockerfile.server
    depends_on: 
      db:
        condition: service_healthy
    ports:
      - 9000:9000
      - 9001:9001

  client:
    image: client
    build: 
      context: .
      dockerfile: ./Dockerfile.client
    depends_on: 
      - server
    ports:
      - 3000:3000
