FROM golang:1.19.0-bullseye

WORKDIR /app/main/server
COPY  ./server /app/main/server

WORKDIR /app/main
COPY  ./main.go .
COPY  ./go.mod .
COPY  ./go.sum .
RUN go mod download
RUN go mod tidy
RUN go build main.go

ENTRYPOINT [ "/app/main/main" ] 